import mongoose from "mongoose";

const messageSchema = new mongoose.Schema(
  {
    //objects---
    senderId: {
      type: mongoose.Schema.Types.ObjectId, //id generated by mongoDb
      ref: "User",
      required: true,
    },
    receiverId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    text: {
      type: String,
    },
    image: {
      type: String,
    },
    video: {
      type: String,
    },
  },
  { timestamps: true }, // CreatedAt, UpdatedAt....
);

const Message = mongoose.model("Message", messageSchema);

export default Message;